[package]
name = "hapi"
version = "0.1.0"
edition = "2021"

[features]
logger = ["log"]
log = ["dep:log"]

[dependencies]
futures = "0.3.30"
hapi-proc = { path = "hapi-proc" }
log = { version = "0.4", optional = true }
